config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :cards

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  validates :title, presence: true
  validates :text, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def new
  end

  def index
    @card = Card.all
  end

  def create
    @card = Card.new(card_params)
    if @card.save
      redirect_to @card
    else
      render 'new'
    end


  end

  def show
    @card = Card.find(params[:id])
  end

  private
  def card_params
    params.require(:card).permit(:title, :text)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cards/create.html.erb
<h1>card created</h1>

app/views/cards/index.html.erb
<h1>Listing Cards</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>

  <% @card.each do |card| %>
    <tr>
      <td><%= card.title %></td>
      <td><%= card.text %></td>
      <td><%= link_to 'Show', card_path(card) %></td>
    </tr>
  <% end %>
</table>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= form_with scope: :card, url: cards_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/cards/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @card.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @card.text %>
</p>

app/views/home/index.html.erb
<h1>HomePageView</h1>
<%= link_to 'Cards list', controller: 'cards' %>
<%= link_to 'Add new card', new_card_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kanbagile</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>